### ISSUE TITLE
Add depth parameter to find links command

### ISSUE THREAD

**Issue by klangner** [AnnaLangner/explorer#10]
Now find_links only looks for links on the first page.
Change the code so it follows the links (go to the next page) and then get links also from this page.

The **depth** parameter decided how deep to go (hon long to follow page links).
Return only unique links.

**Comment by AnnaLangner** [comment]
Should I go to each link on the page and go to the next page? Or should you enter only the first link and download further links from this page?

**Comment by klangner** [comment]
You should follow all links.
