### ISSUE TITLE
Named tuples

### ISSUE THREAD

**Issue by klangner** [AnnaLangner/explorer#5]
Do some refactoring:
  * rename function list_of_all_links to find_links
  * learn about named tuples in python and use them to return information from the find_links function, so the function will return list of LinkInfo tuples.

**Comment by AnnaLangner** [comment]
I don't have an idea how to do this task. I always get the error :
`raise ValueError('Type names and field names must be valid '
ValueError: Type names and field names must be valid identifiers: 'LinkInfo '`

my code:
```
def find_links(driver):  
  links_elem = driver.find_elements_by_tag_name("a")  
  LinkInfo  = namedtuple('LinkInfo ', 'name href')
  return [LinkInfo(name, name.get_attribute('href')) for name in links_elem]
```
I don't understand this...

**Comment by klangner** [comment]
Please commit your code so far

**Comment by AnnaLangner** [comment]
It works but I have this error:

`if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] Nieprawidłowe dojście`

**Comment by klangner** [comment]
Hmm, not sure why. I can't replicate it on my machine. Lets fix all problem first and then check it.

**Comment by AnnaLangner** [comment]
I restarted my computer and ran the script but still got an error after the tuple list:
```
Exception ignored in: <function Popen.__del__ at 0x0318C1D8>
Traceback (most recent call last):
  File "C:\Users\annal\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 945, in __del__
    self._internal_poll(_deadstate=_maxsize)
  File "C:\Users\annal\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1344, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] Nieprawidłowe dojście
```

**Comment by AnnaLangner** [comment]
When I ran script with wikipedia I get an error : 

```
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <a href="//wikimediafoundation.org/"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
```

**Comment by klangner** [comment]
Can you test it with both drivers? (chrome and Firefox). Do you get error on both drivers? Every time?

**Comment by AnnaLangner** [comment]
yes, in both cases

**Comment by AnnaLangner** [comment]
When I added time.sleep(3) after get (url) it started working correctly.

but when I chose google.com I had an error:
```
Exception ignored in: <function Popen.__del__ at 0x03A9C190>
Traceback (most recent call last):
  File "C:\Users\annal\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 945, in __del__
    self._internal_poll(_deadstate=_maxsize)
  File "C:\Users\annal\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1344, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] Nieprawidłowe dojście
```
